name        'role-student-vm'
description 'Configure and update a student vm.'
version     '0.1.0'

depends 'se-chef-solo'
depends 'se-ntp'
depends 'se-update'
depends 'se-xfce'
depends 'se-rdp'
depends 'se-rvm'
depends 'se-rubymine'